version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-clans
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: clans
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api-gateway:
    build: ./clans/api-gateway
    container_name: api-gateway-clans
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - post-service
      - comment-service
      - clan-service
    environment:
      - USER_SERVICE_URL=http://user-service:8080
      - POST_SERVICE_URL=http://post-service:8081
      - COMMENT_SERVICE_URL=http://comment-service:8082
      - CLAN_SERVICE_URL=http://clan-service:8083
      - JWT_SECRET=mysecretkey

  user-service:
    build: ./clans/user-service
    container_name: user-service-clans
    restart: always
    expose:
      - "8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=adminpass
      - DB_NAME=clans

  post-service:
    build: ./clans/post-service
    container_name: post-service-clans
    restart: always
    expose:
      - "8081"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=adminpass
      - DB_NAME=clans

  comment-service:
    build: ./clans/comment-service
    container_name: comment-service-clans
    restart: always
    expose:
      - "8082"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=adminpass
      - DB_NAME=clans

  clan-service:
    build: ./clans/clan-service
    container_name: clan-service-clans
    restart: always
    expose:
      - "8083"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=adminpass
      - DB_NAME=clans

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-clans
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pg_data:
